/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    int flag=0;
    MysqlConnector msg=new MysqlConnector();
    
    public ForgotPassword() {
        initComponents();
        panel_dip.setBackground(new Color(0,0,0,200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_dip = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8Student = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        upassword = new javax.swing.JPasswordField();
        jLabel27 = new javax.swing.JLabel();
        statuslabel = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        SignUpLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        sec_que = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        answer1 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_dip.setBackground(new java.awt.Color(0, 0, 0));
        panel_dip.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Hostel Management System");
        panel_dip.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 400, -1));

        jPanel1.add(panel_dip, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/images.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 500));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8Student.setBackground(new java.awt.Color(36, 47, 65));
        jPanel8Student.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8Student.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 300, 10));

        upassword.setBackground(new java.awt.Color(36, 47, 65));
        upassword.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        upassword.setForeground(new java.awt.Color(57, 113, 177));
        upassword.setToolTipText("");
        upassword.setBorder(null);
        upassword.setCaretColor(new java.awt.Color(255, 255, 255));
        upassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        upassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upasswordActionPerformed(evt);
            }
        });
        jPanel8Student.add(upassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 300, 20));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setText("UPDATED PASSWORD");
        jPanel8Student.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        statuslabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        statuslabel.setForeground(new java.awt.Color(204, 204, 204));
        statuslabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statuslabel.setText("Status");
        statuslabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                statuslabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                statuslabelMouseExited(evt);
            }
        });
        jPanel8Student.add(statuslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 170, -1));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 204, 204));
        jLabel29.setText("Forgot Password");
        jPanel8Student.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 180, -1));

        jPanel13.setBackground(new java.awt.Color(204, 204, 204));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 204, 204));
        jLabel31.setText("EMAIL");
        jPanel13.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        SignUpLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        SignUpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/Refresh_25px.png"))); // NOI18N
        SignUpLabel.setText("Update");
        SignUpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpLabelMouseClicked(evt);
            }
        });
        jPanel13.add(SignUpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        jPanel8Student.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 300, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(57, 113, 177));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel8Student.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 20, -1));

        jLabel34.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(204, 204, 204));
        jLabel34.setText("USERNAME");
        jPanel8Student.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        username.setBackground(new java.awt.Color(36, 47, 65));
        username.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setBorder(null);
        username.setCaretColor(new java.awt.Color(255, 255, 255));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel8Student.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 300, 20));
        jPanel8Student.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 300, 10));

        jLabel35.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 204, 204));
        jLabel35.setText("SECURITY QUESTION");
        jPanel8Student.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        sec_que.setBackground(new java.awt.Color(36, 47, 65));
        sec_que.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        sec_que.setForeground(new java.awt.Color(255, 255, 255));
        sec_que.setBorder(null);
        sec_que.setCaretColor(new java.awt.Color(255, 255, 255));
        sec_que.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec_queActionPerformed(evt);
            }
        });
        jPanel8Student.add(sec_que, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 300, 20));
        jPanel8Student.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 300, 10));

        jLabel36.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(204, 204, 204));
        jLabel36.setText("ANSWER");
        jPanel8Student.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        answer1.setBackground(new java.awt.Color(36, 47, 65));
        answer1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        answer1.setForeground(new java.awt.Color(255, 255, 255));
        answer1.setBorder(null);
        answer1.setCaretColor(new java.awt.Color(255, 255, 255));
        answer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer1ActionPerformed(evt);
            }
        });
        jPanel8Student.add(answer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 300, 20));
        jPanel8Student.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 300, 10));

        jPanel3.add(jPanel8Student, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 500));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 570, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void upasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upasswordActionPerformed

    private void statuslabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statuslabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_statuslabelMouseEntered

    private void statuslabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statuslabelMouseExited

    }//GEN-LAST:event_statuslabelMouseExited

    private void SignUpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpLabelMouseClicked
        // TODO add your handling code here:
        loop1:
        try {
            Connection con=msg.getConnection();
            
            String usern=username.getText();
            String pass=new String(upassword.getPassword());
            String que=sec_que.getText();
            String ans=answer1.getText();
            
            if(usern.equals("") || pass.equals("") || que.equals("") || ans.equals(""))
            {
                JOptionPane.showMessageDialog(this,"Please Check All mandatory Fields","Error",JOptionPane.ERROR_MESSAGE);
                break loop1;
            }
            
            PreparedStatement pst = con.prepareStatement("Select username,secque,answer from student_signup");
            ResultSet re=pst.executeQuery();
            
            while(re.next()){
                if(usern.equals(re.getString(1)) && que.equals(re.getString(2)) && ans.equals(re.getString(3)))
                {
            PreparedStatement pst1 = con.prepareStatement("update student_signup set password=? where username=?");
            
            pst1.setString(1,pass);
            pst1.setString(2,usern);
            
            if(pst1.executeUpdate()==1)
            {
                JOptionPane.showMessageDialog(this,"Password updated successfully");
                new LoginPage().setVisible(true);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Error while updating","Error",JOptionPane.ERROR_MESSAGE);
            }
                }
                flag=1; 
            }
            if(flag==0)
                JOptionPane.showMessageDialog(this,"Invalid username","Error",JOptionPane.ERROR_MESSAGE);
        }
        catch (Exception e) {
        }

    }//GEN-LAST:event_SignUpLabelMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void sec_queActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sec_queActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sec_queActionPerformed

    private void answer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //new ForgotPassword().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SignUpLabel;
    private javax.swing.JTextField answer1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8Student;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JPanel panel_dip;
    private javax.swing.JTextField sec_que;
    private javax.swing.JLabel statuslabel;
    private javax.swing.JPasswordField upassword;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
