/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        jPanel2.setBackground(new Color(0,0,0,200));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelstudenttab = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labeladmintab = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8Student = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        username = new javax.swing.JTextField();
        upassword = new javax.swing.JPasswordField();
        jLabel27 = new javax.swing.JLabel();
        forgotlabel = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jPanel5Admin = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        adminname = new javax.swing.JTextField();
        apassword = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Hostel Management System");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 400, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/images.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 500));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(57, 113, 177));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 20, -1));

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelstudenttab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelstudenttab.setForeground(new java.awt.Color(204, 204, 204));
        labelstudenttab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelstudenttab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/User Group Man Man_25px.png"))); // NOI18N
        labelstudenttab.setText("STUDENT");
        labelstudenttab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelstudenttabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelstudenttabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelstudenttabMouseExited(evt);
            }
        });
        jPanel3.add(labelstudenttab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 250, 70));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 290, 80));

        jPanel4.setBackground(new java.awt.Color(36, 47, 65));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labeladmintab.setBackground(new java.awt.Color(36, 47, 65));
        labeladmintab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labeladmintab.setForeground(new java.awt.Color(204, 204, 204));
        labeladmintab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeladmintab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/Admin_25px.png"))); // NOI18N
        labeladmintab.setText("ADMIN");
        labeladmintab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeladmintabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labeladmintabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labeladmintabMouseExited(evt);
            }
        });
        jPanel4.add(labeladmintab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 240, 70));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 280, 80));

        jPanel6.setLayout(new java.awt.CardLayout());

        jPanel8Student.setBackground(new java.awt.Color(36, 47, 65));
        jPanel8Student.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8Student.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 300, 10));
        jPanel8Student.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 300, 10));

        username.setBackground(new java.awt.Color(36, 47, 65));
        username.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setBorder(null);
        username.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel8Student.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 300, 30));

        upassword.setBackground(new java.awt.Color(36, 47, 65));
        upassword.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        upassword.setForeground(new java.awt.Color(57, 113, 177));
        upassword.setToolTipText("");
        upassword.setBorder(null);
        upassword.setCaretColor(new java.awt.Color(255, 255, 255));
        upassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel8Student.add(upassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 300, 30));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setText("PASSWORD");
        jPanel8Student.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        forgotlabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        forgotlabel.setForeground(new java.awt.Color(204, 204, 204));
        forgotlabel.setText("Forgot Password");
        forgotlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotlabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgotlabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgotlabelMouseExited(evt);
            }
        });
        jPanel8Student.add(forgotlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 204, 204));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/User Group Man Man_25px.png"))); // NOI18N
        jLabel29.setText("Student Login");
        jPanel8Student.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 180, -1));

        jLabel30.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 204, 204));
        jLabel30.setText("USER NAME");
        jPanel8Student.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jPanel13.setBackground(new java.awt.Color(204, 204, 204));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 204, 204));
        jLabel31.setText("EMAIL");
        jPanel13.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabel32.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/Sign Up_25px.png"))); // NOI18N
        jLabel32.setText("SignUp");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        jPanel13.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        jPanel8Student.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 140, 40));

        jPanel15.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/Enter_25px.png"))); // NOI18N
        jLabel36.setText("Login");
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });
        jPanel15.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 40));

        jPanel8Student.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 150, 40));

        jPanel6.add(jPanel8Student, "card3");

        jPanel5Admin.setBackground(new java.awt.Color(36, 47, 65));
        jPanel5Admin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5Admin.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 300, 10));
        jPanel5Admin.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 300, 10));

        adminname.setBackground(new java.awt.Color(36, 47, 65));
        adminname.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        adminname.setForeground(new java.awt.Color(255, 255, 255));
        adminname.setBorder(null);
        adminname.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel5Admin.add(adminname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 300, 30));

        apassword.setBackground(new java.awt.Color(36, 47, 65));
        apassword.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        apassword.setForeground(new java.awt.Color(57, 113, 177));
        apassword.setToolTipText("");
        apassword.setBorder(null);
        apassword.setCaretColor(new java.awt.Color(255, 255, 255));
        apassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel5Admin.add(apassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 300, 30));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("PASSWORD");
        jPanel5Admin.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/Admin_25px.png"))); // NOI18N
        jLabel12.setText("Admin Login");
        jPanel5Admin.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 180, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("USER NAME");
        jPanel5Admin.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("EMAIL");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/Enter_25px.png"))); // NOI18N
        jLabel20.setText("Login");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 300, 40));

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("EMAIL");
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel21.setText("SignUp");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 150, 40));

        jPanel5Admin.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 300, 40));

        jPanel6.add(jPanel5Admin, "card2");

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 570, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void labeladmintabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeladmintabMouseEntered
        // TODO add your handling code here:
       labeladmintab.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(255,255,255)));
    }//GEN-LAST:event_labeladmintabMouseEntered

    private void labeladmintabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeladmintabMouseExited
        // TODO add your handling code here:
        labeladmintab.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(36,47,65)));
    }//GEN-LAST:event_labeladmintabMouseExited

    private void labelstudenttabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelstudenttabMouseEntered
        // TODO add your handling code here:
        labelstudenttab.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(255,255,255)));
    }//GEN-LAST:event_labelstudenttabMouseEntered

    private void labelstudenttabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelstudenttabMouseExited
        // TODO add your handling code here:
        labelstudenttab.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(36,47,65)));
    }//GEN-LAST:event_labelstudenttabMouseExited

    private void labeladmintabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeladmintabMouseClicked
        // TODO add your handling code here:
        jPanel5Admin.setVisible(true);
        jPanel8Student.setVisible(false);
    }//GEN-LAST:event_labeladmintabMouseClicked

    private void labelstudenttabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelstudenttabMouseClicked
        // TODO add your handling code here:
        jPanel8Student.setVisible(true);
        jPanel5Admin.setVisible(false);
    }//GEN-LAST:event_labelstudenttabMouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        new SignUp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        // TODO add your handling code here:
        MysqlConnector msg=new MysqlConnector();
        
        try {
            Connection con=msg.getConnection();
            
            String name=username.getText();
            String pass=new String(upassword.getPassword());
            
            PreparedStatement pst = con.prepareStatement("Select * from student_signup where username=? and password=?");
            
            pst.setString(1,name);
            pst.setString(2,pass);
            
            ResultSet re = pst.executeQuery();
            
            if(re.next())
            {
                String std_id = re.getString(2);
                new StudentHome(std_id).setVisible(true);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Please Check Username and Password","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (Exception e) {
        }
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        MysqlConnector msg=new MysqlConnector();
        
        try {
            Connection con=msg.getConnection();
            
            String name=adminname.getText();
            String pass=new String(apassword.getPassword());
            
            PreparedStatement pst = con.prepareStatement("Select * from admin_login where username=? and password=?");
            
            pst.setString(1,name);                     
            pst.setString(2,pass);
            
            ResultSet re = pst.executeQuery();
            
            if(re.next())
            {
                   String adm_id = re.getString(2);
                   new AdminHome(adm_id).setVisible(true);
                   this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Please Check Username and Password","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (Exception e) {
        }
    }//GEN-LAST:event_jLabel20MouseClicked

    private void forgotlabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotlabelMouseEntered
        // TODO add your handling code here:
        forgotlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(255,255,255)));
    }//GEN-LAST:event_forgotlabelMouseEntered

    private void forgotlabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotlabelMouseExited
        // TODO add your handling code here:
        forgotlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(36,47,65)));
    }//GEN-LAST:event_forgotlabelMouseExited

    private void forgotlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotlabelMouseClicked
        // TODO add your handling code here:
        new ForgotPassword().setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_forgotlabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminname;
    private javax.swing.JPasswordField apassword;
    private javax.swing.JLabel forgotlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5Admin;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8Student;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel labeladmintab;
    private javax.swing.JLabel labelstudenttab;
    private javax.swing.JPasswordField upassword;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
